"""Sphinx configuration for the tambora documentation.

The API reference is generated by autodoc/autosummary directly from tambora's
docstrings, so it can never drift from the installed package. The version this
builds against is whatever ``pip install tambora`` put in the environment --
pin it in ``requirements.txt`` when cutting a docs release.
"""

import os
from datetime import date

import tambora

# -- Project ----------------------------------------------------------------

project = "tambora"
author = "Gabriel Pfaffman"
copyright = f"{date.today().year}, {author}"

release = tambora.__version__
version = release.split("+")[0]

# -- General ----------------------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "myst_nb",
    "sphinx_copybutton",
    "sphinx_design",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "**.ipynb_checkpoints", "Thumbs.db", ".DS_Store"]

# `foo` renders as a Python cross-reference, matching numpy/astropy convention.
default_role = "py:obj"

nitpicky = False

# tambora's own docstrings contain a handful of RST formatting slips (bullet
# lists without a trailing blank line, stray indentation). They render fine and
# are upstream issues, not ours -- but they would fail CI's --fail-on-warning,
# so the docutils parse category is suppressed here. Ours are still reported.
suppress_warnings = ["docutils"]

# -- Autodoc / autosummary --------------------------------------------------

autosummary_generate = True
autosummary_imported_members = False

autodoc_default_options = {
    "members": True,
    "inherited-members": False,
    "show-inheritance": True,
    "member-order": "bysource",
}

# tambora's constructors document their parameters in the class docstring, so
# merge __init__ into the class body rather than emitting a separate entry.
autoclass_content = "both"
autodoc_class_signature = "mixed"
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented_params"

# galpy is an optional dependency at runtime but required to document the galpy
# bridge; if it is genuinely missing, stub it rather than failing the build.
autodoc_mock_imports = []
try:
    import galpy  # noqa: F401
except ImportError:  # pragma: no cover
    autodoc_mock_imports.append("galpy")

napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_use_rtype = False
napoleon_preprocess_types = True

# -- Intersphinx ------------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "galpy": ("https://docs.galpy.org/en/latest/", None),
}

# -- MyST / notebooks -------------------------------------------------------

myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "substitution",
]
myst_heading_anchors = 3

# Cheap notebooks execute on every build so their outputs can never go stale.
# The expensive N-body runs ship with committed outputs and are skipped here --
# see docs/examples/README.md for how to regenerate them.
nb_execution_mode = "cache"
nb_execution_timeout = 900
nb_execution_raise_on_error = True
nb_execution_excludepatterns = [
    # The N-body-heavy notebooks ship with committed outputs, regenerated by
    # tools/build_notebooks.py. Keep this list in sync with EXECUTE there.
    "examples/04-tidal-stream.ipynb",
    "examples/05-tidal-stripping.ipynb",
    "examples/06-stream-track.ipynb",
    "examples/07-stream-gaps.ipynb",
    "examples/08-ring-galaxy.ipynb",
    "examples/09-disk-instability.ipynb",
]

# The .py sources next to each notebook are jupytext mirrors, not pages.
exclude_patterns += ["examples/*.py"]

# -- HTML output ------------------------------------------------------------

html_theme = "furo"
html_title = f"tambora {version}"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_copy_source = True
html_show_sourcelink = True

GITHUB_USER = os.environ.get("TAMBORA_DOCS_GH_USER", "sgpfaff")
GITHUB_DOCS_REPO = os.environ.get("TAMBORA_DOCS_GH_REPO", "tambora-docs")

html_theme_options = {
    "source_repository": f"https://github.com/{GITHUB_USER}/{GITHUB_DOCS_REPO}/",
    "source_branch": "main",
    "source_directory": "docs/",
    "navigation_with_keys": True,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": f"https://github.com/{GITHUB_USER}/tambora",
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0"
                     viewBox="0 0 16 16" width="16" height="16">
                  <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53
                  5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.23.48-2.7-1.07-2.7-1.07-.36-.93-.89-1.18-.89-1.18-.73-.5.06-.49.06-.49.81.06
                  1.23.83 1.23.83.72 1.23 1.89.87 2.35.67.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95
                  0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82a7.6
                  7.6 0 0 1 2-.27c.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16
                  1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54
                  1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                </svg>
            """,
            "class": "",
        },
    ],
}

# -- Substitutions used across the docs -------------------------------------

rst_prolog = f"""
.. |tambora_version| replace:: {release}
"""

myst_substitutions = {
    "gh_user": GITHUB_USER,
    "gh_docs_repo": GITHUB_DOCS_REPO,
    "tambora_version": release,
}
